# Generated by Django 4.0.3 on 2022-06-04 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('home', models.CharField(max_length=64)),
                ('catalog', models.CharField(max_length=64)),
                ('contacts', models.CharField(max_length=64)),
                ('settings', models.CharField(max_length=64)),
            ],
        ),
    ]
